version: '3'

services:
 formulari:
  build: .
  expose:
   - "80"
  volumes:
   - ./app:/var/www/html
  environment:
   - HOST_NAME=gp1f5act14

 lb:
  image: nginx:latest
  volumes:
   - ./nginx.conf:/etc/nginx/nginx.conf:ro
  depends_on:
   - formulari
  ports:
   - "80:8000"
