version: '3'

services:
 formulari:
  image: formulari:3.0
  expose:
   - "80"
  environment:
   - HOST_NAME=gp1f5act14

 lb:
  image: nginx:latest
  volumes:
   - ./nginx.conf:/etc/nginx/nginx.conf:ro
  depends_on:
   - formulari
  ports:
   - "80:8000"
